/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segundatentativa;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanak
 */
public class TelaNumeroNatural extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public TelaNumeroNatural() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tField_numero2 = new javax.swing.JTextField();
        btn_calcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_resultado = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tField_numero1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tField_baseN = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("Numero Natural");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Número Natural 2: ");

        tField_numero2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_calcular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_calcular.setText("Calcular ");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        tbl_resultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_resultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Operação", "Número 1", "Número 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_resultado);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Número Natural 1: ");

        tField_numero1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Número da base N: ");

        tField_baseN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tField_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tField_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btn_calcular))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tField_baseN, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tField_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tField_baseN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tField_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        long numero1;
        long numero2;
        int numeroBaseN;
        try {
            String vOuFDoNumero1 = "";// essa variável é pra salvar as respostas como sim ou não, ao invez de true or false
            String vOuFDoNumero2 = "";// essa variável é pra salvar as respostas como sim ou não, ao invez de true or false

            numero1 = Long.parseLong(tField_numero1.getText());
            numero2 = Long.parseLong(tField_numero2.getText());
            numeroBaseN = Integer.parseInt(tField_baseN.getText());

            NumeroNatural numeroAtual1 = new NumeroNatural(numero1);
            NumeroNatural numeroAtual2 = new NumeroNatural(numero2);

            DefaultTableModel tbl = (DefaultTableModel) tbl_resultado.getModel();

            tbl.setRowCount(0);

//            tbl.addRow(new Object[]{"Numero: ", numero1, numero2});
            tbl.addRow(new Object[]{"Fatorial", numeroAtual1.calcularFatorial(), numeroAtual2.calcularFatorial()});

            vOuFDoNumero1 = transformarBooleanEmString(numeroAtual1.ehNumeroPerfeito());
            vOuFDoNumero2 = transformarBooleanEmString(numeroAtual2.ehNumeroPerfeito());

//vOuFDoNumero1 = String.valueOf(numeroAtual1.ehNumeroPerfeito2());
//vOuFDoNumero2 = String.valueOf(numeroAtual2.ehNumeroPerfeito2());
            tbl.addRow(new Object[]{"É número perfeito?", vOuFDoNumero1, vOuFDoNumero2});

            vOuFDoNumero1 = transformarBooleanEmString(numeroAtual1.ehCapicua());
            vOuFDoNumero2 = transformarBooleanEmString(numeroAtual2.ehCapicua());
            tbl.addRow(new Object[]{"É capicua?", vOuFDoNumero1, vOuFDoNumero2});

            vOuFDoNumero1 = transformarBooleanEmString(numeroAtual1.ehQuadradoPerfeito());
            vOuFDoNumero2 = transformarBooleanEmString(numeroAtual2.ehQuadradoPerfeito());
            tbl.addRow(new Object[]{"É Quadrado perfeito?", vOuFDoNumero1, vOuFDoNumero2});

            vOuFDoNumero1 = transformarBooleanEmString(numeroAtual1.ehNumeroPrimo());
            vOuFDoNumero2 = transformarBooleanEmString(numeroAtual2.ehNumeroPrimo());
            tbl.addRow(new Object[]{"É Número primo?", vOuFDoNumero1, vOuFDoNumero2});

            tbl.addRow(new Object[]{"Convertido para a base 2: ",
                numeroAtual1.converterParaBase2(), numeroAtual2.converterParaBase2()});

            tbl.addRow(new Object[]{"Convertido para a base 8: ",
                numeroAtual1.converterParaBase8(), numeroAtual2.converterParaBase8()});

            tbl.addRow(new Object[]{"Convertido para a base 16: ",
                numeroAtual1.converterParaBase16(), numeroAtual2.converterParaBase16()});

            tbl.addRow(new Object[]{"Convertido para a base N", numeroAtual1.converterParaBaseN(numeroBaseN), numeroAtual2.converterParaBaseN(numeroBaseN)});

////            tbl.addRow(new Object[]{"Máximo Divisor Comum", numeroAtual1.calcularMDC(numero2), numeroAtual2.calcularMDC(numero1)});
            tbl.addRow(new Object[]{"Mínimo Múltiplo Comum",
                numeroAtual1.calcularMMC(numero2), numeroAtual2.calcularMMC(numero1)});

            tbl.addRow(new Object[]{"Máximo Divisor Comum: ", numeroAtual1.calcularMDC(numero2), numeroAtual2.calcularMDC(numero1)});

            vOuFDoNumero1 = transformarBooleanEmString(numeroAtual1.saoPrimosEntreSi(numero2));
            vOuFDoNumero2 = transformarBooleanEmString(numeroAtual2.saoPrimosEntreSi(numero1));
            tbl.addRow(new Object[]{"São primos entre sí?", vOuFDoNumero1, vOuFDoNumero2});

//            tbl_resultado.setModel(tbl);
        } catch (NumberFormatException erro) {

            JOptionPane.showMessageDialog(this, "Digite APENAS números inteiros");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }

    }//GEN-LAST:event_btn_calcularActionPerformed

    public String transformarBooleanEmString(boolean resposta) {
        if (resposta) {
            return "Sim";
        } else {
            return "Não";
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNumeroNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNumeroNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNumeroNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNumeroNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNumeroNatural().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tField_baseN;
    private javax.swing.JTextField tField_numero1;
    private javax.swing.JTextField tField_numero2;
    private javax.swing.JTable tbl_resultado;
    // End of variables declaration//GEN-END:variables
}
